networks:
  services:
   driver: bridge
   name: ${PROJECT}
services:
  pma:
     container_name: ${PROJECT_PMA}
     depends_on:
      - mariadb
     environment: 
      PMA_ABSOLUTE_URI: http://localhost:${PMA_PORT}
      PMA_HOST: mariadb
     image: phpmyadmin/phpmyadmin:${PMA_VERSION-latest}
     networks:
      - services 
     ports: 
      - ${PMA_PORT}:80

  mariadb:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    env_file:
      - .env
    image: database/test-db:local
    networks:
      - services
    ports:
      - 50106:3306
