networks:
  services:
   driver: bridge
   name: ${PROJECT}
services:
  pma:
     container_name: ${PROJECT}-pma
     depends_on:
      - mariadb
     environment: 
      PMA_ABSOLUTE_URI: http://localhost:${PMA_PORT}
      PMA_HOST: mariadb
     image: phpmyadmin/phpmyadmin:${PMA_VERSION-latest}
     networks:
      - services 
     ports: 
      - ${PMA_PORT}:80

  mariadb:
    container_name: ${PROJECT}-mariadb
    env_file: .env
    environment:
      MARIADB_DATABASE: ${PROJECT}
      MARIADB_PASSWORD: ${PROJECT}
      MARIADB_ROOT_PASSWORD: ${PROJECT}
      MARIADB_USER: ${PROJECT}
    image: mariadb:${MARIADB_VERSION-10.11}
    networks:
      - services
    ports:
      - ${MARIADB_PORT}:3306
    volumes:
      - ./mariadb/etc/mysql/conf.d/character_set.cnf:/etc/mysql/conf.d/character-set.cnf
      - ./mariadb/fixtures:/docker-entrypoint-initdb.d
      - mariadb-data:/var/lib/mysql

volumes:
  mariadb-data:
  